### ISSUE TITLE
macOS-specific vignette

### ISSUE THREAD

**Issue by b-rodrigues** [b-rodrigues/rix#101]
I feel we should have a macOS-specific vignette, mostly because RStudio is not available for macOS through nixpkgs. I think it would be better for users if there's a vignette with "macOS" in the title so that they're immediately attracted to it :)

In it, we could then explain how they could use Nix; either using another IDE (or the console), or better, using `with_nix()`. We could then also refer to the vignette you're currently writing @philipp-baumann for more detailed examples. What do you think ?

**Comment by philipp-baumann** [comment]
#109
