### ISSUE TITLE
`rix()`: add `nix_file` argument to write custom `.nix` file

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#103]
Analogous to `with_nix()`, we could add an optional `nix_file` interface, that is by default `NULL`. @b-rodrigues what's your opinion?

**Comment by b-rodrigues** [comment]
What's the use case ?

**Comment by philipp-baumann** [comment]
I think only `with_nix()` currently, when testing different environments in the same folder. But might as well just do renaming in R. Rather than adding more complexity to the interface.

**Comment by b-rodrigues** [comment]
🤔

Do you mean users could set `nix_file = "ahaha.nix"` and have the file called ahahah.nix instead of default.nix? so they could have both in a folder? Wouldn't that be a problem with the `result` symlink? if users would call Nix's garbage collector, wouldn't it get rid of the environment not symlink'ed?

I think it would be cleaner to suggest to users to consider sub-folders for sub-shells, and if they someone really wants to have a shell.nix and a default.nix then they should do it themselves.

**Comment by philipp-baumann** [comment]
> 🤔
> 
> Do you mean users could set `nix_file = "ahaha.nix"` and have the file called ahahah.nix instead of default.nix? so they could have both in a folder? Wouldn't that be a problem with the `result` symlink? if users would call Nix's garbage collector, wouldn't it get rid of the environment not symlink'ed?
> 
> I think it would be cleaner to suggest to users to consider sub-folders for sub-shells, and if they someone really wants to have a shell.nix and a default.nix then they should do it themselves.

Oh yes I see the thing I had in mind does not make sense, as you say with the result symlink. I'll close this one. 
I'll just briefly mention shell.nix in the with_nix() vignette in one sentence with no example, but otherwise I agree we should suggest subfolders for subshells.

**Comment by philipp-baumann** [comment]
> > 🤔
> > Do you mean users could set `nix_file = "ahaha.nix"` and have the file called ahahah.nix instead of default.nix? so they could have both in a folder? Wouldn't that be a problem with the `result` symlink? if users would call Nix's garbage collector, wouldn't it get rid of the environment not symlink'ed?
> > I think it would be cleaner to suggest to users to consider sub-folders for sub-shells, and if they someone really wants to have a shell.nix and a default.nix then they should do it themselves.
> 
> Oh yes I see the thing I had in mind does not make sense, as you say with the result symlink. I'll close this one. I'll just briefly mention shell.nix in the with_nix() vignette in one sentence with no example, but otherwise I agree we should suggest subfolders for subshells.

Thanks for your response :-)
