### ISSUE TITLE
Allow for current packages to be installed directly from CRAN

### ISSUE THREAD

**Issue by b-rodrigues** [b-rodrigues/rix#137]
https://github.com/b-rodrigues/rix/blob/de009f777266a2836da26a5f3e118c7dcf911087/dev/flat_fetchers.Rmd#L85

Specifying package versions only works currently for archived packages. The idea was to say that if the package is current, it is very likely already on nixpkgs, so you wouldn’t want to get it from CRAN. But thinking about it, this might not always be the case, but worse, I think that if we want to be able to write an `renv2nix()` function, we need to be able to "lock" a version of an R package that is current as well, not just archived. In this case, we need to allow something like

```
r_pkgs = "dplyr@1.1.4" 
```

where version 1.1.4 of dplyr is (as of writing) the current version. For example, as of writing, the latest version available on `nixpkgs` of `{marginaleffects}` is version 0.17, but on CRAN, 0.18 is already available. Now, in practice, this rarely matters. But I think we should offer the flexibility for users to install the latest version if they so wish.

**Comment by b-rodrigues** [comment]
The more I think about this, the more I think this is not a good idea. 

I think we may need to have users accept that they should use the current release available on `nixpkgs`. Also, I think that a potential `renv2nix()` should likely not install exactly the same versions of all the packages as in the `renv.lock` file. This is because `renv.lock` files can be all over the place, with an older release of R, but some packages current and other old. Maybe a function like `renv2nix()` should at most install the version of R listed in the `renv.lock` file alongside all the listed packages, but without necessarily forcing exactly the same version. There won't be a single commit of `nixpkgs` that will have all the required versions, so it's going to be a mess.

**Comment by philipp-baumann** [comment]
We might get some hints and approaches from here: https://github.com/NixOS/nixpkgs/blob/nixos-23.11/doc/languages-frameworks/r.section.md

**Comment by b-rodrigues** [comment]
fixed with the possibility of using bleeding_edge environments
