### ISSUE TITLE
Ship a `default.nix` via `inst/extdata`?

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#14]
I thought this might be useful for windows. Basically one could just include "R" version plus {rix} dev version from github. @b-rodrigues what do you think?

**Comment by philipp-baumann** [comment]
It is mostly to avoid cyclic dependencies, since one can only run `rix::rix()` after installation unless doing some magick parsing.

**Comment by philipp-baumann** [comment]
@b-rodrigues aaah `rix::rix()` is only using base R, so easy to do.

**Comment by b-rodrigues** [comment]
I don't understand what you're suggesting?

**Comment by philipp-baumann** [comment]
ok sorry for being unclear. I thought it would be useful on Win or WSL2, respectively, to install and use rix easily. For this, one could use a default .rix file. Is the intention clear?

**Comment by philipp-baumann** [comment]
> ok sorry for being unclear. I thought it would be useful on Win or WSL2, respectively, to install and use rix easily. For this, one could use a default .nix file. Is the intention clear?

mainly because the package depends on httr and curl, which require system commands. With nix, it is really straight-forward to bootstrap without also first installing GNU compiler toolchain.

**Comment by philipp-baumann** [comment]
The disadvantage is of course that one has to manually update (nixpkgs version, R version etc.).

**Comment by b-rodrigues** [comment]
Ah I got it now, sorry! But wouldn't users need to be able to install the package in the first place to get access to inst/default.nix? Which is why I wrote that section in the vignette

https://b-rodrigues.github.io/rix/articles/interactive-use.html#scenario-2-you-install-r-and-rstudio-using-nix

**Comment by philipp-baumann** [comment]
> Ah I got it now, sorry! But wouldn't users need to be able to install the package in the first place to get access to inst/default.nix? Which is why I wrote that section in the vignette
> 
> https://b-rodrigues.github.io/rix/articles/interactive-use.html#scenario-2-you-install-r-and-rstudio-using-nix

true, but one can also just `cat` to `nix-build` in bash, right?

**Comment by philipp-baumann** [comment]
aah now also getting, you are right, cat'ing `inst/extdata/default.nix` would make sense.

**Comment by philipp-baumann** [comment]
@

> Ah I got it now, sorry! But wouldn't users need to be able to install the package in the first place to get access to inst/default.nix? Which is why I wrote that section in the vignette
> 
> https://b-rodrigues.github.io/rix/articles/interactive-use.html#scenario-2-you-install-r-and-rstudio-using-nix

thanks to pointing to that resource. That is actually sufficient for the README, so I will just PR add the link, ok?

**Comment by b-rodrigues** [comment]
yes that’d be great, and you are right as well, we could put that script in inst/ext and then have users run 

```
nix-shell https://github.com/b-rodrigues/rix/master/inst/extdata/default.nix
```

which I believe should drop them in a nix-shell with R and rix installed, so from there they could start building new default.nix files and work from there. What do you think?

**Comment by philipp-baumann** [comment]
> yes that’d be great, and you are right as well, we could put that script in inst/ext and then have users run
> 
> ```
> nix-shell https://github.com/b-rodrigues/rix/master/inst/extdata/default.nix
> ```
> 
> which I believe should drop them in a nix-shell with R and rix installed, so from there they could start building new default.nix files and work from there. What do you think?

I like that approach! Let me draft so users can tap like this. :100:

**Comment by b-rodrigues** [comment]
But let's make clear that rix can be used even if nix is not installed, so windows users could install rix on windows (and the dependencies would be easily installed, because binaries for Windows are available) and generate default.nix files that they could then build with Nix on WSL2 or on another machine with Nix available

**Comment by philipp-baumann** [comment]
> But let's make clear that rix can be used even if nix is not installed, so windows users could install rix on windows (and the dependencies would be easily installed, because binaries for Windows are available) and generate default.nix files that they could then build with Nix on WSL2 or on another machine with Nix available

yes, good point.

**Comment by philipp-baumann** [comment]
Generally like the restructuring. The only thing I thought was that maybe the part after the intro in the Readme could be a bit crispier in terms of lengh 🚀

**Comment by b-rodrigues** [comment]
done
