### ISSUE TITLE
`get_sri_hash_deps()`: alternative/option; locally compute NAR hash via system call to `nix-hash`

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#143]
something like here: https://github.com/NixOS/nixpkgs/blob/01885a071465e223f8f68971f864b15829988504/pkgs/development/r-modules/generate-r-packages.R#L34-L54

**Comment by philipp-baumann** [comment]
It's nice to use your server/service for this, especially if people have not installed Nix yet. If Nix is there, we should maybe also allow local hashing (if this server is on maintenance or people prefer to have their own machine checking).

**Comment by b-rodrigues** [comment]
We could indeed check for Nix and compute the hash locally when available, yes

**Comment by philipp-baumann** [comment]
solved with https://github.com/b-rodrigues/rix/pull/221
