### ISSUE TITLE
`fetchzip()`: allow to look for most recent CRAN package version in "https://cran.r-project.org/src/contrib/<pkg-name>_<version-tag>.tar.gz

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#144]
Currently, this fails because the most recent dplyr version on CRAN, 1.1.4, is not yet in the archive. 

```r
library("rix")

rix_init()

rix(
  r_ver = "4.2.0",
  r_pkgs = "dplyr@1.1.4"
)
# Error in get_sri_hash_deps(repo_url, branch_name = NULL, commit = NULL) : 
  Error in pulling URL: https://cran.r-project.org/src/contrib/Archive/dplyr/dplyr_1.1.4.tar.gz. If it's a Github repo, check the url, branch name and commit. Are these correct? If it's an archived CRAN package, check the name of the package and the version number.
```

Related: #137 

I think we can easily fix that in fetchzip(): https://github.com/b-rodrigues/rix/blob/6dcc9bcb10dcd1baaa9a7d83bab5d1445f231455/R/fetchgit.R#L49

I think we should try to get it from the current packages, too, by trying and alternative URL `https://cran.r-project.org/src/contrib/<pkg-name>_<version-tag>.tar.gz` when its not in the archive (meaning its not on CRAN or it is in the archive URL.

It does not resolve all rPackages issues on Nixpkgs such as the manual patches and system build inputs, but many most recent packages could be installed without waiting for updates via https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/development/r-modules/generate-r-packages.R , manual fixes and pull requests.

**Comment by b-rodrigues** [comment]
A workaround is to install the current version from Github, but this would only work for packages released on Github. I'm not necessarily against the idea (see other thread) but at the same time I don't want to encourage people not to use the packaged version

**Comment by philipp-baumann** [comment]
It could indeed be that builds fail when an `r_pkgs` entry with version tag, which is also the most recent version, depends on other packages at a specific version, and that specific version is not available in the given `r_ver`/Nixpkgs revision. Maybe if we also use fetchzip for that package, that could work, or is indeed an case of flakes with various revisions in build inputs.

**Comment by philipp-baumann** [comment]
> A workaround is to install the current version from Github, but this would only work for packages released on Github. I'm not necessarily against the idea (see other thread) but at the same time I don't want to encourage people not to use the packaged version

I get the point with the non-packaged version. On the other hand, when people use a version tag anyway to get an archive version of a package, this will only apply the patches of rPackages except for the buildInputs of package which will go over Nixpkgs revision? Or am i misunderstanding something?

**Comment by b-rodrigues** [comment]
No you’re right, but here I figure that there’s less of an expectation that installing an old version must work. Also, this is what is said in the vignette:

```
The above expression will install R version 4.2.1, and [dplyr](https://dplyr.tidyverse.org/) at version 0.8.0 and [janitor](https://github.com/sfirke/janitor) at version 1.0.0. This can be useful, especially for packages that have been archived, but otherwise, this feature should ideally be used sparingly. If you want to reconstruct an environment as it was around 2019, use the version of R that was current at that time. This will ensure that every package that gets installed is at a version compatible with that version of R, which might not be the case if you need to install a very old version of one particular package.
```

Regarding latest versions: we could perhaps maintain a fork of nixpkgs with daily auto-updates as does @jbedo https://github.com/jbedo/nixpkgs/tree/R
and tell people to use that, if they absolutely need bleeding edge versions. But again, I’m not sure if it would be worth the effort.

**Comment by philipp-baumann** [comment]
> No you’re right, but here I figure that there’s less of an expectation that installing an old version must work. Also, this is what is said in the vignette:
> 
> > The above expression will install R version 4.2.1, and [dplyr](https://dplyr.tidyverse.org/) at version 0.8.0 and [janitor](https://github.com/sfirke/janitor) at version 1.0.0. This can be useful, especially for packages that have been archived, but otherwise, this feature should ideally be used sparingly. If you want to reconstruct an environment as it was around 2019, use the version of R that was current at that time. This will ensure that every package that gets installed is at a version compatible with that version of R, which might not be the case if you need to install a very old version of one particular package.


I think it's a likely case, either coming from {renv} or bringing a default.nix config to {renv} (of course with the systems libraries limitation of renv). It's a small thing to add, and if we already allow this for historic packages why not for current CRAN. 

> 
> Regarding latest versions: we could perhaps maintain a fork of nixpkgs with daily auto-updates as does @jbedo https://github.com/jbedo/nixpkgs/tree/R and tell people to use that, if they absolutely need bleeding edge versions. But again, I’m not sure if it would be worth the effort.

Yeah that's true. Thanks for the reference :-) now i get it, he's doing that over a CRON job. but i wonder then would it not make sense to to have an periodic update of https://github.com/NixOS/nixpkgs/blob/nixos-23.11/pkgs/development/r-modules/cran-packages.nix (of course without the fixes which can't be automated).

**Comment by philipp-baumann** [comment]
given {renv} would be used and there is no cross-dependency conflicts between the packages and everything else is installed, we kind of have green light. but yeah it's not forseeable if the entire thing builds.

**Comment by b-rodrigues** [comment]
Well, we now got our own daily CRAN and Bioconductor update, so I was thinking to add a "bleeding_edge" as in `rix(r_version = "bleeding_edge")` that would point towards it, maybe with a warning to the user.

**Comment by b-rodrigues** [comment]
I think we can close this now, as it is now possible to have bleeding edge packages using our daily biilds
