### ISSUE TITLE
Unable to install the gifski package

### ISSUE THREAD

**Issue by gueyenono** [b-rodrigues/rix#150]
I want to create an animation with the [`{gganimate}` package](https://github.com/thomasp85/gganimate), however, it is not working correctly. Here is the R code:

```
library(ggplot2)
library(gganimate)

ggplot(mtcars, aes(factor(cyl), mpg)) + 
  geom_boxplot() + 
  # Here comes the gganimate code
  transition_states(
    gear,
    transition_length = 2,
    state_length = 1
  ) +
  enter_fade() + 
  exit_shrink() +
  ease_aes('sine-in-out')
```

Instead of producing an animation, my code creates a bunch of png files in the working directory. After doing a bit of research, I found out that this is caused by the absence of the [`{gifski}`](https://github.com/r-rust/gifski) and [`{png}`](https://cran.r-project.org/web/packages/png/index.html) packages. I found the solution [here](https://stackoverflow.com/questions/58991580/gganimate-returns-png-files-but-no-animated-object).

My issue is that I am not able to install the `{gifski}` package. Below is how I  generated the `default.nix` file:

```
library(rix)

rix(
	r_ver = "4.3.1",
	r_pkgs = c("gganimate", "ggplot2", "gifski", "png"),
	git_pkgs = NULL,
	ide = "rstudio",
	project_path = getwd(),
	shell_hook = "
	  export QT_XCB_GL_INTEGRATION=none
	",
	overwrite = TRUE,
	print = TRUE
)
```

However I get the following error:

```
ERROR: cargoHash or cargoSha256 is out of date

Cargo.lock is not the same in /build/cargo-deps-vendor.tar.gz

To fix the issue:
1. Set cargoHash/cargoSha256 to an empty string: 
2. Build the derivation and wait for it to fail with a hash mismatch
3. Copy the got: sha256-... value back into the cargoHash field
   You should have: cargoHash = sha256-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=;

error: builder for '/nix/store/x866kkf11p9db3vrxnjbqa9paxb1hqa1-r-gifski-1.12.0-1.drv' failed with exit code 1;
       last 10 log lines:
       > ERROR: cargoHash or cargoSha256 is out of date
       >
       > Cargo.lock is not the same in /build/cargo-deps-vendor.tar.gz
       >
       > To fix the issue:
       > 1. Set cargoHash/cargoSha256 to an empty string: 
       > 2. Build the derivation and wait for it to fail with a hash mismatch
       > 3. Copy the got: sha256-... value back into the cargoHash field
       >    You should have: cargoHash = sha256-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=;
       >
       For full logs, run 'nix-store -l /nix/store/x866kkf11p9db3vrxnjbqa9paxb1hqa1-r-gifski-1.12.0-1.drv'.
error: 1 dependencies of derivation '/nix/store/ks563f4y2997bzdrsn09knd7wki2xhav-nix-shell.drv' failed to build
```

The error code seems to provide a solution to my problem, however, I am not yet knowledgeable enough in the ways of Nix to implement it  easily. Thank you for providing a solution.

**Comment by b-rodrigues** [comment]
gifski was indeed broken and was fixed since, you can use "latest" as the r_ver and it should work.

**Comment by gueyenono** [comment]
Thank you for your prompt response. Is there any difference between passing `"latest"` to `r_ver` and just specifying the latest R version as given by `available_r()`? The solution seems to suggest so.

**Comment by b-rodrigues** [comment]
"latest" gives you the very latest commit from nixpkgs, while specifying a versions always points to the same commit containing that version.

**Comment by gueyenono** [comment]
If this is the case, then, I would like to know how much of a "good practice" it is to use `"latest"` for reproducibility. Because if I understand correctly, the same code may produce different results with time?

**Comment by b-rodrigues** [comment]
yes, you’ll have to then go to your generated default.nix and use that commit in the call to rix() to regenerate the same file

**Comment by gueyenono** [comment]
This is very well noted, Bruno. Again, I appreciate the prompt responses.
