### ISSUE TITLE
Todos in code

### ISSUE THREAD

**Issue by b-rodrigues** [b-rodrigues/rix#151]
https://github.com/b-rodrigues/rix/blob/8e9f94049b070e45e91b2cc9d6ca3fe63c2182c9/dev/flat_with_nix.Rmd#L267

https://github.com/b-rodrigues/rix/blob/8e9f94049b070e45e91b2cc9d6ca3fe63c2182c9/dev/flat_nix_build.Rmd#L116

**Comment by philipp-baumann** [comment]
addressed https://github.com/b-rodrigues/rix/commit/600f913fe8807ffdf35844b05a6e213917807a86
