### ISSUE TITLE
Use official Nixpkgs repo and not bleeding edge fork for rix's top level `default.nix`

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#164]
For the development environment in `default.nix` at the root of {rix}, I'd prefer to pin the official https://github.com/NixOS/nixpkgs repo. Packages can break there too but it is way less likely because it is peer-reviewed and tested on Hydra, while the bleeding-edge fork is experimental. Just to have way less surprises and if we mess anything up there, happens. ;-)

**Comment by b-rodrigues** [comment]
We need it to be bleeding edge though, because we need to develop against the current state of CRAN
