### ISSUE TITLE
Support the Magic Nix Cache Github Action

### ISSUE THREAD

**Issue by brancengregory** [b-rodrigues/rix#167]
https://github.com/DeterminateSystems/magic-nix-cache-action

**Comment by brancengregory** [comment]
I think a helper function analogous to `ga_cachix` would be great

**Comment by b-rodrigues** [comment]
thanks added it to the workflow for cachix https://github.com/b-rodrigues/rix/commit/31c43d5a54721ade32cfcb4692336f8997d20b28
