### ISSUE TITLE
YAML alternative to `rix()`

### ISSUE THREAD

**Issue by brancengregory** [b-rodrigues/rix#168]
I read in your blog you'd like the option to have yaml specification of the environment. I think that's a cool idea, and recommend the strategy that `{pointblank}` implements--the interface is great.

https://github.com/rstudio/pointblank

**Comment by b-rodrigues** [comment]
yeah at the time I thought it could be nice, but I'm not so sure now. rix() does a lot of things under the hood for the user, and I don't think a yaml interface would be as comfortable.

**Comment by brancengregory** [comment]
Makes sense!
