### ISSUE TITLE
{fusen}: short info on dev/contribution

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#2]
Hi @b-rodrigues , for possible future contributors it might be nice to briefly add a very short dev section in README, where you could mention {fusen}-based workflow to develop the package etc. What do you think?

**Comment by b-rodrigues** [comment]
you’re right, fixed with a39713ad118334c6acaad952aaa3d30673d57131

**Comment by philipp-baumann** [comment]
nice!
