### ISSUE TITLE
Installing packages from R running inside nix uses local `~/.R/Makevars`

### ISSUE THREAD

**Issue by eliocamp** [b-rodrigues/rix#211]
This might not be an issue, but more like a surprise. I would've expected the rsession running in the nix shell to be isolated from the system, but when I tried to install a bunch of packages from source, it failed because it was trying to use `ccache` (form my local `~/.R/Makevars` file) which wasn't installed. 

Is this expected behaviour?

**Comment by b-rodrigues** [comment]
Nix is isolated at build time, not at run time. So it can and will look for stuff in PATH. to have isolation at run time,use rix::rix_init() in your projects root folder

**Comment by b-rodrigues** [comment]
Also, install your packages at build time instead,either from git or from a local tar.gz

**Comment by eliocamp** [comment]
Yep, I was testing what would happen if I installed packages at runtime emulating what I would do in normal data exploration, adding packages as I need them.
