### ISSUE TITLE
Small typo in README

### ISSUE THREAD

**Issue by gorkang** [b-rodrigues/rix#233]
"Its purpose is to solve a complex problem: defining instructions on how to build software packages and manage configurations in a declarative and way" ->  "Its purpose is to solve a complex problem: defining instructions on how to build software packages and manage configurations in a declarative ~and~ way"

**Comment by b-rodrigues** [comment]
Thank you!

fixed in 911181413e85aa0624232506de8c78ef5ae8208a and 692aa3cfeb97c50ff720bda4eff53276b8ad3ece
