### ISSUE TITLE
Document options(rix.sri_hash=) in rix()’s documentation

### ISSUE THREAD

**Issue by b-rodrigues** [b-rodrigues/rix#256]
https://github.com/b-rodrigues/rix/blob/710c9d224bef94195426447e78b71aee6e81f6c2/R/nix_hash.R#L248

This is for now not documented in a user-facing function

**Comment by b-rodrigues** [comment]
https://github.com/b-rodrigues/rix/pull/257

**Comment by philipp-baumann** [comment]
solved with #257
