### ISSUE TITLE
documentation: git packages need three or four-item lists?

### ISSUE THREAD

**Issue by Kupac** [b-rodrigues/rix#268]
It is not clear whether git packages are defined by three or four element lists:
Examples:
- [fetchers.R](https://github.com/b-rodrigues/rix/blob/0461ac3bc7e4ce92d39763552243dbd3988754d3/R/fetchers.R#L257-L259)
- [rix.R](https://github.com/b-rodrigues/rix/blob/0461ac3bc7e4ce92d39763552243dbd3988754d3/R/rix.R#L78-L80): in this case, the documentation also refers to github, but it probably (hopefully) works with any git resource. Maybe better not to advertise any one of them.

**Comment by b-rodrigues** [comment]
This is fixed in current master

Regarding mentioning Github, you're right is should work with any service, but I have to test it

**Comment by philipp-baumann** [comment]
> Regarding mentioning Github, you're right is should work with any service, but I have to test it

can we close this, @Kupac, since there is now an open issue and an git branch that seems to address other server-based git repositories like GitLab etc. #278

**Comment by Kupac** [comment]
Sure, of course! I thought it was closed already!
