### ISSUE TITLE
Release {rix} 0.9.0

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#269]
- [ ]

**Comment by b-rodrigues** [comment]
Something like?


# rix 0.9.0 (2024-07-21)

## User-facing changes

- Breaking change: it is not necessary to provide the branchName argument for Github packages anymore
  
## Chores

- Source code now follows tidyverse style guide thanks to `{styler}`
- Github Actions: we now use rhub2 for checking the package
- Documentation: explain `options(rix.sri_hash)` in `rix::rix()`

**Comment by philipp-baumann** [comment]
done with https://github.com/b-rodrigues/rix/commit/f86cd9b04d8fc81f0429415093c90d34db18f6f8
