### ISSUE TITLE
Introduce semantic versioning

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#30]
I though we could use [{fledge}](https://fledge.cynkra.com) to pin down versions of {rix} and implement smooth change management. This is of course opinionated, but personally I really find it straightforward to use it for my own packages.

So essentially it means two simple commands for most of the cases.

```r
# every merge commit done into master gets a "* implement feature A" commit message
fledge::bump_version()
# then manually fine-tune auto-generated `NEWS.md`
fledge::finalize_version()
# to finish; then when pushing it is git tagged
```

At the moment {rix} is at development stage in version 0.0.0.9000. However, since the core is stable while a lot of new functionality is arriving, it would be very nice to communicate progress to users. 

@b-rodrigues what do you think of that?

**Comment by b-rodrigues** [comment]
I wasn’t aware this was a thing, and am curious and willing to learn! Hope I won’t forget to do it

**Comment by philipp-baumann** [comment]
> I wasn’t aware this was a thing, and am curious and willing to learn! Hope I won’t forget to do it

it is quite easy to get a grip of. We could give it a try and see if it would be useful/becomes a routine.

**Comment by philipp-baumann** [comment]
closing this one as we have started versioning and `NEWS.md` facilitated via {fledge}.
