### ISSUE TITLE
rix goes r-universe?

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#4]
Just a small suggestion: it would be nice if {rix} arrives on r-universe. Since it only requires a personal repo of yours called "universe" and a `packages.json` config with {rix} listed, would be cool!

**Comment by b-rodrigues** [comment]
I'm not sure, what are the benefits? Is it just about discoverability?

**Comment by philipp-baumann** [comment]
up! thanks @b-rodrigues
