### ISSUE TITLE
`nix-shell` fails for `inst/exdata/default.nix` on MacOS: `LOCALE_ARCHIVE`: error "cannot coerce null to a string"

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#48]
see https://fosstodon.org/@jimgar/110883444629542663

```sh
nix-shell --expr "$(curl -sl https://raw.githubusercontent.com/b-rodrigues/rix/master/inst/extdata/default.nix)"
```

**Comment by philipp-baumann** [comment]
see also https://search.nixos.org/packages?channel=23.05&show=darwin.locale&from=0&size=50&sort=relevance&type=packages&query=darwin.locale

**Comment by philipp-baumann** [comment]
https://github.com/b-rodrigues/rix/commit/0275dcc087335b1b84bb00e5ec824a4cb0e2b4f5
this is a temporary fix; warning startup in R; failed setting different local category sections. `LC_CTYPE`, etc.

**Comment by philipp-baumann** [comment]
@b-rodrigues maybe one way to solve to have a shellHook of `R` starting up with a distinct locale (either via ENVVAR or Sys.setenv(). We might need some `sed` magic to change the Nix expression from `inst/exdata/default.nix`. This is for sure still hacky, but maybe until we have a flakes solution.

**Comment by philipp-baumann** [comment]
notes to myself: https://rstudio.github.io/r-manuals/r-admin/Internationalization.html

**Comment by jimgar** [comment]
Thanks for looking into this so quickly, folks. 

Whatever you have done has worked :)

**Comment by b-rodrigues** [comment]
Thanks for the feedback! We will need to make some adjustments for macOS then

**Comment by jimgar** [comment]
Ok, that would be much appreciated @b-rodrigues !

**Comment by b-rodrigues** [comment]
ok, so now it should be working, maybe to make extra sure everything works as intended, in the folder where you ran the command: 

```
nix-shell --expr "$(curl -sl https://raw.githubusercontent.com/b-rodrigues/rix/master/inst/extdata/default.nix)"
```

look for a file called simply `result`. Remove that, and then run:

```
nix-store --gc
```

this will remove everything. Then, rerun the command:

```
nix-shell --expr "$(curl -sl https://raw.githubusercontent.com/b-rodrigues/rix/master/inst/extdata/default.nix)"
```

this should now install the patched version. Many thanks for testing!

**Comment by philipp-baumann** [comment]
Thanks for testing @b-rodrigues and @jimgar :-) I will today create an official GitHub release {rix} v0.1.2 with the patch.

**Comment by philipp-baumann** [comment]
@jimgar I'll close this one soon, just making sure that the three lines Bruno has suggested to run works for you. Did this work as well? Thanks

**Comment by jimgar** [comment]
Hi both. I couldn't see `result` anywhere. I'm not sure if that would be expected just from the lines above. I can see this comes up in part 2 of the blog post, so maybe I just didn't get to it yet? I haven't run `nix-build`, for example, which seems to generate `result`?

Running `nix-store --gc` removed the store, and then after running default.nix via curl I was dropped into an R session again. So that still seems to work!

**Comment by philipp-baumann** [comment]
> Hi both. I couldn't see `result` anywhere. I'm not sure if that would be expected just from the lines above. I can see this comes up in part 2 of the blog post, so maybe I just didn't get to it yet? I haven't run `nix-build`, for example, which seems to generate `result`?
> 
> Running `nix-store --gc` removed the store, and then after running default.nix via curl I was dropped into an R session again. So that still seems to work!

great to hear it now works :-) you will only see `result` symlink store once you run `nix-build` or you do this via `rix::nix_build(project_path = "<path-to-dir-where-default.nix-is>")`. Does this help or do you need more infos?

**Comment by b-rodrigues** [comment]
ah yes right, since the build failed you wouldn't see result! Cool, happy it works now!

**Comment by jimgar** [comment]
yeah that's fine @philipp-baumann , it makes sense. I hadn't got that far into the blog post because of the original problem thus no `result`.

**Comment by philipp-baumann** [comment]
@jimgar closing this one, but just open a new tickets for suggestions or other issues.
