### ISSUE TITLE
README: new "From quickstart to deep dive" top section

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#51]
note to myself: To have a quick entry section for code-affine people. Later will show code of bootstrap helper like `make_launcher()`. For now it will be installing {rix} and bumping Rix R env straight-forwardly. This means moving small parts in README.

**Comment by b-rodrigues** [comment]
I've added these lines, what do you think?

https://github.com/b-rodrigues/rix/blob/506784bd4350625978fdd6f51a0b4327c9d4f6e2/README.md?plain=1#L68

**Comment by philipp-baumann** [comment]
> I've added these lines, what do you think?
> 
> https://github.com/b-rodrigues/rix/blob/506784bd4350625978fdd6f51a0b4327c9d4f6e2/README.md?plain=1#L68

sounds good.
