### ISSUE TITLE
Switch to parse `r_nix_revs` from https://www.nixhub.io/packages/R

### ISSUE THREAD

**Issue by philipp-baumann** [b-rodrigues/rix#58]
@b-rodrigues here we even get R 4.3.1 :-)

**Comment by b-rodrigues** [comment]
So we can use "4.3.1" and "latest", to get the latest commit of nixpkgs instead of current

**Comment by philipp-baumann** [comment]
> So we can use "4.3.1" and "latest", to get the latest commit of nixpkgs instead of current

yeah! I guess for compatibility purposes, we still keep the `r_nix_revs` pkg data you derive via https://github.com/b-rodrigues/rix/blob/master/dev/save_r_nix_revs.Rmd , right? I'd make a new dataset via PR, naming it e.g. like `"r_nix_revs_nixhub"`

**Comment by philipp-baumann** [comment]
I'd make a short parser similar to what you did, then we could also expose/export this function in the package so that users can query, too, if they like.

**Comment by b-rodrigues** [comment]
> > So we can use "4.3.1" and "latest", to get the latest commit of nixpkgs instead of current
> 
> yeah! I guess for compatibility purposes, we still keep the `r_nix_revs` pkg data you derive via https://github.com/b-rodrigues/rix/blob/master/dev/save_r_nix_revs.Rmd , right? I'd make a new dataset via PR, naming it e.g. like `"r_nix_revs_nixhub"`

I'm not sure we need to keep the old data, we're still in development so I don't have an issue introducing breaking changes

**Comment by philipp-baumann** [comment]
sounds good to me! True and also due to unique hash in nix config files there is no problem with that.
