### ISSUE TITLE
Vignette "Authoring LaTeX documents"

### ISSUE THREAD

**Issue by b-rodrigues** [b-rodrigues/rix#73]
Following 1bd327c7cf315d22ab69865b6fc96c943cd97bd4 we now need a vignette explaining how to install texlive packages for authoring documents.

**Comment by philipp-baumann** [comment]
Awesome, thanks for the addition @b-rodrigues . I just bumped {rix} v0.3.0.

**Comment by b-rodrigues** [comment]
done 1295d74408ba593cdf68ae8442eaba1f0cf56935
