### ISSUE TITLE
Failed to execute 'nix-build' (Permission denied) error when running Quickstart code

### ISSUE THREAD

**Issue by pcantalupo** [b-rodrigues/rix#78]
Hello,

I ran the quickstart code from https://b-rodrigues.github.io/rix/#from-quickstart-to-deep-dive and got an error:

```
> library("rix")
> file.copy(
+   from = system.file("extdata", "default.nix", package = "rix"),
+   to = ".", overwrite = TRUE
+ )
[1] TRUE
> nix_build(project_path = ".")
Launching `nix-build ./default.nix` in blocking mode
Error: Failed to execute 'nix-build' (Permission denied)
```

Here is my sessionInfo

```
 sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6.9

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rix_0.3.1

loaded via a namespace (and not attached):
[1] httr_1.4.5     compiler_4.2.2 R6_2.5.1       tools_4.2.2    jsonlite_1.8.4
[6] sys_3.4.1  
```

**Comment by b-rodrigues** [comment]
What OS are you on? Is the nix running? try running 'nix repl' in a console, does it start?

**Comment by b-rodrigues** [comment]
Is nix running? try 'nix repl' in a terminal, does it start?

**Comment by pcantalupo** [comment]
My apologies....I'm just now realizing that `nix` is required. I read a twitter post about `rix` and thought it worked out of the box by installing the package.

**Comment by b-rodrigues** [comment]
You don't have to have Nix to generate expressions, but will have to have it for building

**Comment by philipp-baumann** [comment]
Hi @pcantalupo what we could indeed do is improving the error message that `nix_build()` requires nix being installed in your case. Cheers

**Comment by philipp-baumann** [comment]
reopened so that I remember to implement a specific error message.

**Comment by b-rodrigues** [comment]
@philipp-baumann I think is is done now, no?
