### ISSUE TITLE
glibclocales for macOS?

### ISSUE THREAD

**Issue by b-rodrigues** [b-rodrigues/rix#84]
https://github.com/b-rodrigues/rix/blob/da9b2398ae02871c53591b1a306092267b560dab/inst/extdata/default.nix#L34

gotta say I’m confused, how does this work? As far as I can see, glibclocalesUTF-8 is not available for darwin. Why does that not result in an error?

**Comment by philipp-baumann** [comment]
> https://github.com/b-rodrigues/rix/blob/da9b2398ae02871c53591b1a306092267b560dab/inst/extdata/default.nix#L34
> 
> gotta say I’m confused, how does this work? As far as I can see, glibclocalesUTF-8 is not available for darwin. Why does that not result in an error?

that is a very good question. Somehow, I failed to make the import conditional on linux, via `mkIf`, but it did  not work syntax wise. Do you have an idea how we could express this?

**Comment by b-rodrigues** [comment]
i guess we could

let glibcLocalesUtf8 = and here we set glibcLocalesUtf8 if linux, and empty string if darwin

but apparently that doesn’t seem to be a problem, since the CI/CD on darwin passes?

**Comment by philipp-baumann** [comment]
> i guess we could
> 
> ```
> let glibcLocalesUtf8 = and here we set glibcLocalesUtf8 if linux, and empty string if darwin
>   in ....
> ```
> 
> but apparently that doesn’t seem to be a problem, since the CI/CD on darwin passes?

cool, I'll try and once it works post in the main nix R matrix channel to see if someone knows better why.

**Comment by philipp-baumann** [comment]
This works all fine, closing :-)
